### ISSUE TITLE
-Pattern doesn't work

### ISSUE THREAD

**Issue by Womabre** [kzrnm/Kurukuru-PowerShell#8]
Not matter what pattern type I use. "Dots", "Moon" etc.. it always shows the sequence with the slashed and dash.
"/\-"

**Comment by kzrnm** [comment]
This is due to the limitations of Kurukuru. Please refer to the Kurukuru documentation for more information.

> NOTE: Sadly, today's almost Windows are configured as using non-Unicode (UTF-8) code page and "Command Prompt" doesn't support font fallback yet.☹ If you want to see non-ASCII spinners, you can change the code page either by System.Console.OutputEncoding = System.Text.Encoding.UTF8 or by running chcp 65001 command and then use [ConEmu](https://conemu.github.io/) or [mintty](https://mintty.github.io/) to display the fallback font.

https://github.com/mayuki/Kurukuru#aware-non-unicode-codepage-on-windows-environment

The problem should be resolved by executing the following code.

```powershell
[System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
```

**Comment by Womabre** [comment]
Thanks! That works! Maybe something worth adding tot the readme.
